# Install Strimzi CRDs and operator first:
#   kubectl create -f https://strimzi.io/install/latest?namespace=youtrack-dev
#
# Or via Helm:
#   helm repo add strimzi https://strimzi.io/charts/
#   helm install strimzi-operator strimzi/strimzi-kafka-operator -n youtrack-dev

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: youtrack-kafka
  namespace: youtrack-dev
spec:
  kafka:
    version: 3.7.0
    replicas: 1  # Dev environment — single broker
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
      log.retention.hours: 168       # 7 days
      log.segment.bytes: 1073741824  # 1 GB
      num.partitions: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true  # Clean up on delete in dev
    resources:
      requests:
        memory: 1Gi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: "1"
  zookeeper:
    replicas: 1  # Single ZK node for dev
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m
  entityOperator:
    topicOperator: {}
    userOperator: {}

---
# Example topic — adjust to match what your YouTrack integration needs
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: youtrack-events
  namespace: youtrack-dev
  labels:
    strimzi.io/cluster: youtrack-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000   # 7 days
    cleanup.policy: delete
