apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-data
  namespace: youtrack-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: standard  # Uncomment and adjust for your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-conf
  namespace: youtrack-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-logs
  namespace: youtrack-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-backups
  namespace: youtrack-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: youtrack
  namespace: youtrack-dev
  labels:
    app: youtrack
spec:
  serviceName: youtrack
  replicas: 1
  selector:
    matchLabels:
      app: youtrack
  template:
    metadata:
      labels:
        app: youtrack
    spec:
      securityContext:
        runAsUser: 13001
        runAsGroup: 13001
        fsGroup: 13001
      containers:
        - name: youtrack
          image: jetbrains/youtrack:2024.3.55417
          ports:
            - containerPort: 8080
              name: http
          env:
            # JVM heap — adjust based on your team size
            - name: JAVA_HEAP_SIZE
              value: "1024m"
            # Base URL — update to match your ingress/domain
            - name: YOUTRACK_BASE_URL
              value: "https://youtrack-dev.example.com"
          volumeMounts:
            - name: data
              mountPath: /opt/youtrack/data
            - name: conf
              mountPath: /opt/youtrack/conf
            - name: logs
              mountPath: /opt/youtrack/logs
            - name: backups
              mountPath: /opt/youtrack/backups
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /api/config
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/config
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/config
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30  # Up to 5 min startup
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: youtrack-data
        - name: conf
          persistentVolumeClaim:
            claimName: youtrack-conf
        - name: logs
          persistentVolumeClaim:
            claimName: youtrack-logs
        - name: backups
          persistentVolumeClaim:
            claimName: youtrack-backups

---
apiVersion: v1
kind: Service
metadata:
  name: youtrack
  namespace: youtrack-dev
  labels:
    app: youtrack
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: youtrack

---
# Ingress — adjust for your ingress controller (nginx shown here)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtrack
  namespace: youtrack-dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    # cert-manager.io/cluster-issuer: letsencrypt-prod  # Uncomment if using cert-manager
spec:
  ingressClassName: nginx
  rules:
    - host: youtrack-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: youtrack
                port:
                  number: 8080
  # tls:
  #   - hosts:
  #       - youtrack-dev.example.com
  #     secretName: youtrack-tls
